-- MySQL Script generated by MySQL Workbench
-- Wed Jan 14 10:40:55 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
CREATE DATABASE IF NOT EXISTS aivleTK;
USE aivleTK;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aivleTK
-- -----------------------------------------------------sys_configsys_config

-- -----------------------------------------------------
-- Table `company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `company` ;

CREATE TABLE IF NOT EXISTS `company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `license` VARCHAR(200) NULL,
  `performance_history` VARCHAR(200) NULL,
  PRIMARY KEY (`company_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NULL,
  `email` VARCHAR(25) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `role` BIT(2) NOT NULL COMMENT '00:일반,01:기업,10:관리자,11:휴면',
  `birth` DATE NOT NULL,
  `question` VARCHAR(50) NOT NULL,
  `answer` VARCHAR(50) NOT NULL,
  `tag` BIT(4) NULL COMMENT 'sys_configsys_config0000~0111:일반 유저 태그, 1000~1111: 기업 유저 태그',
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_company1_idx` (`company_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bid` ;

CREATE TABLE IF NOT EXISTS `bid` (
  `bid_id` INT NOT NULL AUTO_INCREMENT,
  `bid_real_id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `content` VARCHAR(400) NOT NULL DEFAULT '',
  `start_date` TIMESTAMP NOT NULL,
  `end_date` TIMESTAMP NOT NULL,
  `open_date` TIMESTAMP NOT NULL,
  `region` VARCHAR(10) NOT NULL,
  `price` BIGINT NOT NULL,
  `organization` VARCHAR(15) NOT NULL,
  `bid_URL` VARCHAR(300) NOT NULL,
  `bid_report_URL` VARCHAR(300) NULL,
  PRIMARY KEY (`bid_id`),
  UNIQUE INDEX `bid_id_UNIQUE` (`bid_id` ASC) VISIBLE,
  UNIQUE INDEX `bid_real_id_UNIQUE` (`bid_real_id` ASC) VISIBLE)
ENGINE = InnoDB;

ALTER TABLE bid MODIFY COLUMN end_date DATETIME NULL;
ALTER TABLE bid MODIFY COLUMN start_date DATETIME NULL;
-- -----------------------------------------------------
-- Table `alarm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alarm` ;

CREATE TABLE IF NOT EXISTS `alarm` (
  `alarm_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `bid_id` INT NOT NULL,
  `alarm_content` VARCHAR(100) NOT NULL,
  `alarm_date` TIMESTAMP NULL,
  PRIMARY KEY (`alarm_id`),
  INDEX `fk_alarm_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_alarm_bid1_idx` (`bid_id` ASC) VISIBLE,
  UNIQUE INDEX `alarm_id_UNIQUE` (`alarm_id` ASC) VISIBLE,
  CONSTRAINT `fk_alarm_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alarm_bid1`
    FOREIGN KEY (`bid_id`)
    REFERENCES `bid` (`bid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wishlist` ;

CREATE TABLE IF NOT EXISTS `wishlist` (
  `wishlist_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `bid_id` INT NOT NULL,
  `wishlist_content` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`wishlist_id`),
  INDEX `fk_alarm_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_alarm_bid1_idx` (`bid_id` ASC) VISIBLE,
  CONSTRAINT `fk_alarm_user0`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alarm_bid10`
    FOREIGN KEY (`bid_id`)
    REFERENCES `bid` (`bid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analysis_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analysis_result` ;

CREATE TABLE IF NOT EXISTS `analysis_result` (
  `analysis_result_id` INT NOT NULL AUTO_INCREMENT,
  `bid_id` INT NOT NULL,
  `golden_rate` DECIMAL NOT NULL,
  `predicted_price` BIGINT NOT NULL,
  `avg_rate` DECIMAL NOT NULL,
  `analysis_date` DATETIME NOT NULL,
  `file_path` VARCHAR(200) NOT NULL,
  `analysis_content` VARCHAR(1000) NULL,
  PRIMARY KEY (`analysis_result_id`),
  INDEX `fk_analysis_result_bid1_idx` (`bid_id` ASC) VISIBLE,
  UNIQUE INDEX `predicted_price_UNIQUE` (`predicted_price` ASC) VISIBLE,
  CONSTRAINT `fk_analysis_result_bid1`
    FOREIGN KEY (`bid_id`)
    REFERENCES `bid` (`bid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bid_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bid_log` ;

CREATE TABLE IF NOT EXISTS `bid_log` (
  `bid_log_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `bid_id` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `price` BIGINT NULL,
  PRIMARY KEY (`bid_log_id`),
  INDEX `fk_bid_log_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_bid_log_bid1_idx` (`bid_id` ASC) VISIBLE,
  UNIQUE INDEX `bid_log_id_UNIQUE` (`bid_log_id` ASC) VISIBLE,
  CONSTRAINT `fk_bid_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bid_log_bid1`
    FOREIGN KEY (`bid_id`)
    REFERENCES `bid` (`bid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `board` ;

CREATE TABLE IF NOT EXISTS `board` (
  `board_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `like_count` INT NOT NULL,
  `view_count` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `file_path` VARCHAR(300) NULL,
  PRIMARY KEY (`board_id`),
  INDEX `fk_board_user1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `board_id_UNIQUE` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_board_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comment` ;

CREATE TABLE IF NOT EXISTS `comment` (
  `comment_id` INT NOT NULL,
  `content` VARCHAR(300) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `bid_id` INT NULL,
  `board_id` INT NULL,
  `parent_comment_id` INT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comment_bid1_idx` (`bid_id` ASC) VISIBLE,
  INDEX `fk_comment_board1_idx` (`board_id` ASC) VISIBLE,
  INDEX `fk_comment_comment1_idx` (`parent_comment_id` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`user_user_id` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_bid1`
    FOREIGN KEY (`bid_id`)
    REFERENCES `bid` (`bid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `board` (`board_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_comment1`
    FOREIGN KEY (`parent_comment_id`)
    REFERENCES `comment` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
