# -*- coding: utf-8 -*-
"""빅프 llm 파이프라인

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxX__wd30bLxV1NL1MaipW76KO03VlKJ
"""

!pip install fastapi uvicorn pyngrok



# llm.py
import os

USE_OPENAI = True  # 🔁 True로 바꾸면 실제 LLM 사용

def call_llm(prompt: str) -> str:
    if USE_OPENAI:
        from openai import OpenAI
        client = OpenAI(api_key=os.environ[""])

        resp = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0
        )
        return resp.choices[0].message.content.strip()

    # ✅ Mock LLM (PoC용)
    if "Classify" in prompt:
        if "요약" in prompt:
            return "report_summary"
        if "보고서" in prompt:
            return "report_qa"
        if "기능" in prompt:
            return "site_feature_qa"
        return "general_chat"

    return "이것은 LLM의 응답 예시입니다."

# intent_router.py
#from llm import call_llm

INTENT_PROMPT = """
Classify the user request into one of:
- general_chat
- report_summary
- report_qa
- site_feature_qa

Return only the label.
"""

def route_intent(query: str) -> str:
    result = call_llm(INTENT_PROMPT + "\nUser: " + query)
    return result.strip()

# rag.py
def summarize_report():
    return "📄 보고서 요약입니다: 이 보고서는 매출 증가와 리스크를 다룹니다."

def qa_report(query: str):
    return f"📌 보고서에서 '{query}'에 대한 답변입니다."

# site_qa.py
def site_feature_answer(query: str):
    return "🧭 이 사이트는 보고서 요약, 질의응답, 챗봇 기능을 제공합니다."

# app.py
from fastapi import FastAPI
from pydantic import BaseModel
'''
from intent_router import route_intent
from rag import summarize_report, qa_report
from site_qa import site_feature_answer
from llm import call_llm
'''
app = FastAPI(title="LLM Pipeline PoC")

class ChatRequest(BaseModel):
    query: str

@app.get("/")
def root():
    return {"status": "running"}

@app.post("/chat")
def chat(req: ChatRequest):
    intent = route_intent(req.query)

    if intent == "report_summary":
        answer = summarize_report()

    elif intent == "report_qa":
        answer = qa_report(req.query)

    elif intent == "site_feature_qa":
        answer = site_feature_answer(req.query)

    else:
        answer = call_llm(req.query)

    return {
        "intent": intent,
        "answer": answer
    }

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="LLM Pipeline PoC")

class ChatRequest(BaseModel):
    query: str

@app.get("/")
def root():
    return {"status": "running"}

@app.post("/chat")
def chat(req: ChatRequest):
    query = req.query
    intent = route_intent(query)

    if intent == "report_summary":
        answer = summarize_report()

    elif intent == "report_qa":
        answer = qa_report(query)

    elif intent == "site_feature_qa":
        answer = site_feature_answer(query)

    else:
        answer = call_llm(query)

    return {
        "intent": intent,
        "answer": answer
    }

from fastapi.middleware.cors import CORSMiddleware
# 모든 출처(origin)에서의 접근을 허용하기 위한 설정
origins = ["*"]

# CORS(Cross-Origin Resource Sharing) 미들웨어 추가
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,        # 모든 도메인에서의 요청 허용
    allow_credentials=True,     # 쿠키, 인증 정보 포함 요청 허용
    allow_methods=["GET", "POST", "PUT", "DELETE"],  # 허용할 HTTP 메서드
    allow_headers=origins,        # 모든 HTTP 헤더 허용
)

from pyngrok import ngrok
import nest_asyncio
from uvicorn import Config, Server

#from app import app

nest_asyncio.apply()

ngrok.set_auth_token("")
public_url = ngrok.connect(8000)
print("🌍 Public URL:", public_url)

config = Config(app=app, host="0.0.0.0", port=8000)
server = Server(config)

await server.serve()

from fastapi import FastAPI
from pydantic import BaseModel

# ------------------
# Mock LLM
# ------------------
from openai import OpenAI
os.environ["OPENAI_API_KEY"] =""
api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

def call_llm(prompt: str) -> str:
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are an intent classifier and assistant."},
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )
    return response.choices[0].message.content.strip()

# ------------------
# Intent Router
# ------------------
def route_intent(query: str) -> str:
    prompt = f"""
    Classify the user request into one of:
    - general_chat
    - report_summary
    - report_qa
    - site_feature_qa

    User: {query}
    """
    return call_llm(prompt)

# ------------------
# RAG / Site QA
# ------------------
def summarize_report():
    return "📄 보고서 요약입니다."

def qa_report(query: str):
    return f"📌 보고서 질의 응답: {query}"

def site_feature_answer(query: str):
    return "🧭 이 사이트는 보고서 요약과 질의응답을 제공합니다."

# ------------------
# FastAPI App
# ------------------
app = FastAPI()

class ChatRequest(BaseModel):
    query: str

@app.get("/")
def root():
    return {"status": "running"}

@app.post("/chat")
def chat(req: ChatRequest):
    intent = route_intent(req.query)

    if intent == "report_summary":
        answer = summarize_report()
    elif intent == "report_qa":
        answer = qa_report(req.query)
    elif intent == "site_feature_qa":
        answer = site_feature_answer(req.query)
    else:
        answer = call_llm(req.query)

    return {
        "intent": intent,
        "answer": answer
    }

from pyngrok import ngrok
import nest_asyncio
from uvicorn import Config, Server

nest_asyncio.apply()

ngrok.set_auth_token("")
print(ngrok.connect(8000))

config = Config(app=app, host="0.0.0.0", port=8000)
server = Server(config)

await server.serve()